const food =[
    'apple',
    'almond',
    'anchovies',
    'apricots',
    'artichokes',
    'avacado',
    'arugula',
    'apricot',
    'banana',
    'bacon',
    'bagel',
    'bread',
    'basil',
    'butter',
    'beans',
    'black beans',
    'beef',
    'biscuits',
    'blackberry',
    'brussel sprouts',
    'blueberry',
    'brownie',
    'brocolli',
    'cabbage',
    'cream',
    'cake',
    'celery',
    'carrot',
    'cauliflower',
    'cheese',
    'cherry',
    'chicken',
    'chili',
    'chocolate',
    'coconut',
    'coffee',
    'cod',
    'corn',
    'crab',
    'curry',
    'clam',
    'cucumber',
    'dumpling',
    'dough',
    'duck',
    'eggs',
    'fish',
    'fries',
    'fried chicken',
    'flour',
    'fruit salad',
    'french toast',
    'grape',
    'guava',
    'graham crackers',
    'grapefruit',
    'greek yogurt',
    'greek salad',
    'gravy',
    'gingerbread',
    'garlic',
    'grilled cheese',
    'ginger',
    'green pepper',
    'green onion',
    'ham',
    'hummus',
    'honey',
    'ice cream',
    'jalapeno',
    'jam',
    'jello',
    'jellybeans',
    'jerky',
    'kale',
    'kimchi',
    'kiwi',
    'key lime pie',
    'kabob',
    'lamb',
    'lasagna',
    'lobster',
    'lemon',
    'lime',
    'linguini',
    'lettuce',
    'meatball',
    'meatloaf',
    'melon',
    'milk',
    'mango',
    'mushroom',
    'nuts',
    'nutella',
    'noodles',
    'naan',
    'orange',
    'oyster',
    'onion',
    'olives',
    'oreo',
    'oatmeal',
    'pancake',
    'papaya',
    'peach',
    'potato',
    'pear',
    'pea',
    'pineapple',
    'plum',
    'pomegranate',
    'pepper',
    'quinoa',
    'quesadilla',
    'radish',
    'raspberry',
    'ravioli',
    'raisin',
    'rice',
    'ribs',
    'relish',
    'salmon',
    'salad',
    'soy beans',
    'sausage',
    'salami',
    'spinach',
    'strawberry',
    'soup',
    'salt',
    'sugar',
    'sandwich',
    'syrup',
    'salsa',
    'shrimp',
    'sushi',
    'steak',
    'squash',
    'sweet potato',
    'scallops',
    'tacos',
    'turkey',
    'toast',
    'tomato',
    'tofu',
    'tater tots',
    'tuna',
    'tangerine',
    't-bone',
    'udon',
    'vanilla',
    'veal',
    'vegetable',
    'vinegar',
    'watermelon',
    'wheat',
    'wasabi',
    'waffle',
    'walnut',
    'watercress',
    'wild rice',
    'whipped cream',
    'wonton',
    'yogurt',
    'yams',
    'zucchini',
]

export {food}